### PR TITLE
Pixelpipe: refactor raster mask a bit + more alert

### LINKED ISSUE #482: Bug: Segfault when a raster-masked module is bellow its source
### Code of Conduct

- [x] I have read this document and I accept the conditions

### Search previous report

- [x] I have searched my issue

### Computer's operating system

Windows 7, 8, 10, or 11

### What GPU do you have ?

Nvidia

### Ansel version

0.0.0+1602~g892dad90a9

### Type of binary

Self-compiled (GCC or Clang)

### What happened?

I know it's supposed to be forbidden, but I moved mistakenly a module with raster mask bellow the module providing the mask source.

Instead of doing nothing and/or alerting the user we can't do that, I had a segfault:
https://pastebin.com/kKwnVms1

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?

I don't know

### Previous Ansel version that use to work

_No response_

### Output of ansel -d all

```shell

```

### Backtrace

```shell

```

### PR DESCRIPTION
**Pull request by Jiyone**
This avoid segfault in some case when raster masks are not found, and tells the user about it with some hints.

fix #482

### CODE REVIEW

File: src/develop/pixelpipe_hb.c [hunk 1]
```diff
@@ -2625,16 +2625,92 @@ void dt_dev_pixelpipe_get_roi_in(dt_dev_pixelpipe_t *pipe, struct dt_develop_t *
...
+ * @param source_piece
+ * @param current_piece
+ * @param target_module
+ * @return gboolean TRUE when all is good, FALSE otherwise.
+ */
+static gboolean _dt_dev_raster_mask_check(dt_dev_pixelpipe_iop_t *source_piece, dt_dev_pixelpipe_iop_t 
+  *current_piece, const dt_iop_module_t *target_module)
+{
+  gboolean success = TRUE;
+  const gchar *clean_target_name = delete_underscore(target_module->name());
```
Comment (aurelienpierre) [inline src/develop/pixelpipe_hb.c:2641]: can't be const because you need to free it after

File: src/develop/pixelpipe_hb.c [hunk 2]
```diff
@@ -2625,16 +2625,92 @@ void dt_dev_pixelpipe_get_roi_in(dt_dev_pixelpipe_t *pipe, struct dt_develop_t *
...
+  const gchar *target_name = g_strdup_printf("%s (%s)", clean_target_name, target_module->multi_name);
```
Comment (aurelienpierre) [inline src/develop/pixelpipe_hb.c:2642]: can't be const because you need to free it after

File: src/develop/pixelpipe_hb.c [hunk 3]
```diff
@@ -2625,16 +2625,92 @@ void dt_dev_pixelpipe_get_roi_in(dt_dev_pixelpipe_t *pipe, struct dt_develop_t *
...
+                      target_name, target_name, hint ? hint : "");
+    g_free(hint);
+
+    fprintf(stderr, "[raster masks] no source module for module %s could be found\n", target_name);
+    success = FALSE;
+  }
+
+  if(success && !source_piece->enabled)
+  {
+    const gchar *clean_source_name = delete_underscore(source_piece->module->name());
```
Comment (aurelienpierre) [inline src/develop/pixelpipe_hb.c:2684]: same, const vs. free

**Review by aurelienpierre — CHANGES_REQUESTED** [review]

**Comment by aurelienpierre** [comment]
Thanks !
