### PR TITLE
Fix offset on the circle in Tone EQ  + refactor INNER_PADDING definition

### LINKED ISSUE #493: Bug: Horizontal offset betwee Circle and mouse cursor in Tone EQ
### Code of Conduct

- [x] I have read this document and I accept the conditions

### Search previous report

- [x] I have searched my issue

### Computer's operating system

Windows 7, 8, 10, or 11

### What GPU do you have ?

I don't know

### Ansel version

1a5027b

### Type of binary

Self-compiled (GCC or Clang)

### What happened?

I don't know if I'm the only one who gets this but the circle in Tone EQ has an offset with the mouse cursor.
See on this screen: we don't see the cursor but it is pointing on the node's center:

Image

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?

I don't know

### Previous Ansel version that use to work

_No response_

### Output of ansel -d all

```shell

```

### Backtrace

```shell

```

### PR DESCRIPTION
**Pull request by Jiyone**
This fix #493 as the computation of the `x` coordinate of the circle was obsolete.

I also fixed 2 TODOs which tells to use the bauhaus `INNER_PADDING` macro instead of `4`.

### CODE REVIEW

File: src/iop/toneequal.c [hunk 1]
```diff
@@ -2463,8 +2464,9 @@ static inline gboolean _init_drawing(dt_iop_module_t *const restrict self, GtkWi
   g->sign_width = g->ink.width / 2.0;
 
   // Set the sizes, margins and paddings
-  g->inner_padding = 4; // TODO: INNER_PADDING value as defined in bauhaus.c macros, sync them
+  g->inner_padding = INNER_PADDING;
   g->inset = g->inner_padding + darktable.bauhaus->quad_width;
+  g->graph_left_space = g->line_height - g->inner_padding;
```
Comment (aurelienpierre) [inline src/iop/toneequal.c:2469]: Where is this variable used ?

Comment (Jiyone) [reply src/iop/toneequal.c:2469]: Oops i forgot to add one line 🫢

**Comment by aurelienpierre** [comment]
Thanks !
